export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const RESET_CURRENT_TRACK = 'RESET_CURRENT_TRACK';
export const SET_CURRENT_PLAYLIST = 'SET_CURRENT_PLAYLIST';
export const SET_NEXT_TRACK = 'SET_NEXT_TRACK';
export const SET_PREV_TRACK = 'SET_PREV_TRACK';
export const SET_SHUFFLED = 'SET_SHUFFLED';
export const GENERATE_SHUFFLED_PLAYLIST = 'GENERATE_SHUFFLED_PLAYLIST';